apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kedacore/keda/releases/download/v2.15.1/keda-2.15.1.yaml
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.1/components.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls
    target:
      group: apps
      version: v1
      kind: Deployment
      name: metrics-server
      namespace: kube-system
